#!/bin/sh
rm upgrade/po/vi_VN.po
rm upgrade/po/tr_TR.po
rm upgrade/po/sr_YU.po
rm upgrade/po/nl_NL.po
rm upgrade/po/it_IT.po
rm upgrade/po/fr_FR.po
rm upgrade/po/de_DE.po
rm upgrade/po/cs_CZ.po
rm upgrade/po/bg_BG.po
rm upgrade/locale/vi_VN/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/vi_VN/LC_MESSAGES
rmdir upgrade/locale/vi_VN
rm upgrade/locale/tr_TR/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/tr_TR/LC_MESSAGES
rmdir upgrade/locale/tr_TR
rm upgrade/locale/sr_YU/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/sr_YU/LC_MESSAGES
rmdir upgrade/locale/sr_YU
rm upgrade/locale/nl_NL/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/nl_NL/LC_MESSAGES
rmdir upgrade/locale/nl_NL
rm upgrade/locale/it_IT/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/it_IT/LC_MESSAGES
rmdir upgrade/locale/it_IT
rm upgrade/locale/fr_FR/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/fr_FR/LC_MESSAGES
rmdir upgrade/locale/fr_FR
rm upgrade/locale/de_DE/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/de_DE/LC_MESSAGES
rmdir upgrade/locale/de_DE
rm upgrade/locale/cs_CZ/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/cs_CZ/LC_MESSAGES
rmdir upgrade/locale/cs_CZ
rm upgrade/locale/bg_BG/LC_MESSAGES/gallery2_upgrade.mo
rmdir upgrade/locale/bg_BG/LC_MESSAGES
rmdir upgrade/locale/bg_BG
rm themes/tile/po/vi_VN.po
rm themes/tile/po/tr_TR.po
rm themes/tile/po/sv_SE.po
rm themes/tile/po/sr_YU.po
rm themes/tile/po/ru_RU.po
rm themes/tile/po/no_NO.po
rm themes/tile/po/nl_NL.po
rm themes/tile/po/it_IT.po
rm themes/tile/po/is_IS.po
rm themes/tile/po/fr_FR.po
rm themes/tile/po/de_DE.po
rm themes/tile/po/da_DK.po
rm themes/tile/po/cs_CZ.po
rm themes/tile/locale/vi_VN/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/vi_VN/LC_MESSAGES
rmdir themes/tile/locale/vi_VN
rm themes/tile/locale/tr_TR/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/tr_TR/LC_MESSAGES
rmdir themes/tile/locale/tr_TR
rm themes/tile/locale/sv_SE/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/sv_SE/LC_MESSAGES
rmdir themes/tile/locale/sv_SE
rm themes/tile/locale/sr_YU/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/sr_YU/LC_MESSAGES
rmdir themes/tile/locale/sr_YU
rm themes/tile/locale/ru_RU/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/ru_RU/LC_MESSAGES
rmdir themes/tile/locale/ru_RU
rm themes/tile/locale/no_NO/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/no_NO/LC_MESSAGES
rmdir themes/tile/locale/no_NO
rm themes/tile/locale/nl_NL/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/nl_NL/LC_MESSAGES
rmdir themes/tile/locale/nl_NL
rm themes/tile/locale/it_IT/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/it_IT/LC_MESSAGES
rmdir themes/tile/locale/it_IT
rm themes/tile/locale/is_IS/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/is_IS/LC_MESSAGES
rmdir themes/tile/locale/is_IS
rm themes/tile/locale/fr_FR/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/fr_FR/LC_MESSAGES
rmdir themes/tile/locale/fr_FR
rm themes/tile/locale/de_DE/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/de_DE/LC_MESSAGES
rmdir themes/tile/locale/de_DE
rm themes/tile/locale/da_DK/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/da_DK/LC_MESSAGES
rmdir themes/tile/locale/da_DK
rm themes/tile/locale/cs_CZ/LC_MESSAGES/themes_tile.mo
rmdir themes/tile/locale/cs_CZ/LC_MESSAGES
rmdir themes/tile/locale/cs_CZ
rm themes/slider/po/vi_VN.po
rm themes/slider/po/tr_TR.po
rm themes/slider/po/sv_SE.po
rm themes/slider/po/sr_YU.po
rm themes/slider/po/ru_RU.po
rm themes/slider/po/no_NO.po
rm themes/slider/po/nl_NL.po
rm themes/slider/po/it_IT.po
rm themes/slider/po/is_IS.po
rm themes/slider/po/fr_FR.po
rm themes/slider/po/de_DE.po
rm themes/slider/po/da_DK.po
rm themes/slider/po/cs_CZ.po
rm themes/slider/locale/vi_VN/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/vi_VN/LC_MESSAGES
rmdir themes/slider/locale/vi_VN
rm themes/slider/locale/tr_TR/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/tr_TR/LC_MESSAGES
rmdir themes/slider/locale/tr_TR
rm themes/slider/locale/sv_SE/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/sv_SE/LC_MESSAGES
rmdir themes/slider/locale/sv_SE
rm themes/slider/locale/sr_YU/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/sr_YU/LC_MESSAGES
rmdir themes/slider/locale/sr_YU
rm themes/slider/locale/ru_RU/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/ru_RU/LC_MESSAGES
rmdir themes/slider/locale/ru_RU
rm themes/slider/locale/no_NO/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/no_NO/LC_MESSAGES
rmdir themes/slider/locale/no_NO
rm themes/slider/locale/nl_NL/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/nl_NL/LC_MESSAGES
rmdir themes/slider/locale/nl_NL
rm themes/slider/locale/it_IT/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/it_IT/LC_MESSAGES
rmdir themes/slider/locale/it_IT
rm themes/slider/locale/is_IS/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/is_IS/LC_MESSAGES
rmdir themes/slider/locale/is_IS
rm themes/slider/locale/fr_FR/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/fr_FR/LC_MESSAGES
rmdir themes/slider/locale/fr_FR
rm themes/slider/locale/de_DE/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/de_DE/LC_MESSAGES
rmdir themes/slider/locale/de_DE
rm themes/slider/locale/da_DK/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/da_DK/LC_MESSAGES
rmdir themes/slider/locale/da_DK
rm themes/slider/locale/cs_CZ/LC_MESSAGES/themes_slider.mo
rmdir themes/slider/locale/cs_CZ/LC_MESSAGES
rmdir themes/slider/locale/cs_CZ
rm themes/siriux/po/vi_VN.po
rm themes/siriux/po/tr_TR.po
rm themes/siriux/po/sv_SE.po
rm themes/siriux/po/sr_YU.po
rm themes/siriux/po/ru_RU.po
rm themes/siriux/po/pt_PT.po
rm themes/siriux/po/pl_PL.po
rm themes/siriux/po/no_NO.po
rm themes/siriux/po/nl_NL.po
rm themes/siriux/po/ja_JP.po
rm themes/siriux/po/it_IT.po
rm themes/siriux/po/is_IS.po
rm themes/siriux/po/hu_HU.po
rm themes/siriux/po/he_IL.po
rm themes/siriux/po/ga_IE.po
rm themes/siriux/po/fr_FR.po
rm themes/siriux/po/fi_FI.po
rm themes/siriux/po/el_GR.po
rm themes/siriux/po/de_DE.po
rm themes/siriux/po/da_DK.po
rm themes/siriux/po/cs_CZ.po
rm themes/siriux/locale/vi_VN/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/vi_VN/LC_MESSAGES
rmdir themes/siriux/locale/vi_VN
rm themes/siriux/locale/tr_TR/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/tr_TR/LC_MESSAGES
rmdir themes/siriux/locale/tr_TR
rm themes/siriux/locale/sv_SE/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/sv_SE/LC_MESSAGES
rmdir themes/siriux/locale/sv_SE
rm themes/siriux/locale/sr_YU/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/sr_YU/LC_MESSAGES
rmdir themes/siriux/locale/sr_YU
rm themes/siriux/locale/ru_RU/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/ru_RU/LC_MESSAGES
rmdir themes/siriux/locale/ru_RU
rm themes/siriux/locale/pt_PT/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/pt_PT/LC_MESSAGES
rmdir themes/siriux/locale/pt_PT
rm themes/siriux/locale/pl_PL/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/pl_PL/LC_MESSAGES
rmdir themes/siriux/locale/pl_PL
rm themes/siriux/locale/no_NO/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/no_NO/LC_MESSAGES
rmdir themes/siriux/locale/no_NO
rm themes/siriux/locale/nl_NL/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/nl_NL/LC_MESSAGES
rmdir themes/siriux/locale/nl_NL
rm themes/siriux/locale/ja_JP/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/ja_JP/LC_MESSAGES
rmdir themes/siriux/locale/ja_JP
rm themes/siriux/locale/it_IT/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/it_IT/LC_MESSAGES
rmdir themes/siriux/locale/it_IT
rm themes/siriux/locale/is_IS/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/is_IS/LC_MESSAGES
rmdir themes/siriux/locale/is_IS
rm themes/siriux/locale/hu_HU/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/hu_HU/LC_MESSAGES
rmdir themes/siriux/locale/hu_HU
rm themes/siriux/locale/he_IL/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/he_IL/LC_MESSAGES
rmdir themes/siriux/locale/he_IL
rm themes/siriux/locale/ga_IE/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/ga_IE/LC_MESSAGES
rmdir themes/siriux/locale/ga_IE
rm themes/siriux/locale/fr_FR/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/fr_FR/LC_MESSAGES
rmdir themes/siriux/locale/fr_FR
rm themes/siriux/locale/fi_FI/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/fi_FI/LC_MESSAGES
rmdir themes/siriux/locale/fi_FI
rm themes/siriux/locale/el_GR/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/el_GR/LC_MESSAGES
rmdir themes/siriux/locale/el_GR
rm themes/siriux/locale/de_DE/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/de_DE/LC_MESSAGES
rmdir themes/siriux/locale/de_DE
rm themes/siriux/locale/da_DK/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/da_DK/LC_MESSAGES
rmdir themes/siriux/locale/da_DK
rm themes/siriux/locale/cs_CZ/LC_MESSAGES/themes_siriux.mo
rmdir themes/siriux/locale/cs_CZ/LC_MESSAGES
rmdir themes/siriux/locale/cs_CZ
rm themes/siriux/images/background.png
rm themes/siriux/images/background-header.png
rm themes/siriux/images/background-footer.png
rm themes/siriux/images/background-content.png
rm themes/matrix/po/vi_VN.po
rm themes/matrix/po/tr_TR.po
rm themes/matrix/po/sv_SE.po
rm themes/matrix/po/sr_YU.po
rm themes/matrix/po/ru_RU.po
rm themes/matrix/po/pt_PT.po
rm themes/matrix/po/pl_PL.po
rm themes/matrix/po/no_NO.po
rm themes/matrix/po/nl_NL.po
rm themes/matrix/po/ja_JP.po
rm themes/matrix/po/it_IT.po
rm themes/matrix/po/is_IS.po
rm themes/matrix/po/hu_HU.po
rm themes/matrix/po/he_IL.po
rm themes/matrix/po/ga_IE.po
rm themes/matrix/po/fr_FR.po
rm themes/matrix/po/fi_FI.po
rm themes/matrix/po/el_GR.po
rm themes/matrix/po/de_DE.po
rm themes/matrix/po/da_DK.po
rm themes/matrix/po/cs_CZ.po
rm themes/matrix/po/ar_SA.po
rm themes/matrix/locale/vi_VN/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/vi_VN/LC_MESSAGES
rmdir themes/matrix/locale/vi_VN
rm themes/matrix/locale/tr_TR/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/tr_TR/LC_MESSAGES
rmdir themes/matrix/locale/tr_TR
rm themes/matrix/locale/sv_SE/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/sv_SE/LC_MESSAGES
rmdir themes/matrix/locale/sv_SE
rm themes/matrix/locale/sr_YU/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/sr_YU/LC_MESSAGES
rmdir themes/matrix/locale/sr_YU
rm themes/matrix/locale/ru_RU/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/ru_RU/LC_MESSAGES
rmdir themes/matrix/locale/ru_RU
rm themes/matrix/locale/pt_PT/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/pt_PT/LC_MESSAGES
rmdir themes/matrix/locale/pt_PT
rm themes/matrix/locale/pl_PL/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/pl_PL/LC_MESSAGES
rmdir themes/matrix/locale/pl_PL
rm themes/matrix/locale/no_NO/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/no_NO/LC_MESSAGES
rmdir themes/matrix/locale/no_NO
rm themes/matrix/locale/nl_NL/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/nl_NL/LC_MESSAGES
rmdir themes/matrix/locale/nl_NL
rm themes/matrix/locale/ja_JP/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/ja_JP/LC_MESSAGES
rmdir themes/matrix/locale/ja_JP
rm themes/matrix/locale/it_IT/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/it_IT/LC_MESSAGES
rmdir themes/matrix/locale/it_IT
rm themes/matrix/locale/is_IS/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/is_IS/LC_MESSAGES
rmdir themes/matrix/locale/is_IS
rm themes/matrix/locale/hu_HU/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/hu_HU/LC_MESSAGES
rmdir themes/matrix/locale/hu_HU
rm themes/matrix/locale/he_IL/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/he_IL/LC_MESSAGES
rmdir themes/matrix/locale/he_IL
rm themes/matrix/locale/ga_IE/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/ga_IE/LC_MESSAGES
rmdir themes/matrix/locale/ga_IE
rm themes/matrix/locale/fr_FR/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/fr_FR/LC_MESSAGES
rmdir themes/matrix/locale/fr_FR
rm themes/matrix/locale/fi_FI/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/fi_FI/LC_MESSAGES
rmdir themes/matrix/locale/fi_FI
rm themes/matrix/locale/el_GR/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/el_GR/LC_MESSAGES
rmdir themes/matrix/locale/el_GR
rm themes/matrix/locale/de_DE/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/de_DE/LC_MESSAGES
rmdir themes/matrix/locale/de_DE
rm themes/matrix/locale/da_DK/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/da_DK/LC_MESSAGES
rmdir themes/matrix/locale/da_DK
rm themes/matrix/locale/cs_CZ/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/cs_CZ/LC_MESSAGES
rmdir themes/matrix/locale/cs_CZ
rm themes/matrix/locale/ar_SA/LC_MESSAGES/themes_matrix.mo
rmdir themes/matrix/locale/ar_SA/LC_MESSAGES
rmdir themes/matrix/locale/ar_SA
rm themes/hybrid/po/vi_VN.po
rm themes/hybrid/po/tr_TR.po
rm themes/hybrid/po/sv_SE.po
rm themes/hybrid/po/sr_YU.po
rm themes/hybrid/po/no_NO.po
rm themes/hybrid/po/nl_NL.po
rm themes/hybrid/po/it_IT.po
rm themes/hybrid/po/is_IS.po
rm themes/hybrid/po/fr_FR.po
rm themes/hybrid/po/de_DE.po
rm themes/hybrid/po/da_DK.po
rm themes/hybrid/po/cs_CZ.po
rm themes/hybrid/locale/vi_VN/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/vi_VN/LC_MESSAGES
rmdir themes/hybrid/locale/vi_VN
rm themes/hybrid/locale/tr_TR/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/tr_TR/LC_MESSAGES
rmdir themes/hybrid/locale/tr_TR
rm themes/hybrid/locale/sv_SE/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/sv_SE/LC_MESSAGES
rmdir themes/hybrid/locale/sv_SE
rm themes/hybrid/locale/sr_YU/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/sr_YU/LC_MESSAGES
rmdir themes/hybrid/locale/sr_YU
rm themes/hybrid/locale/no_NO/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/no_NO/LC_MESSAGES
rmdir themes/hybrid/locale/no_NO
rm themes/hybrid/locale/nl_NL/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/nl_NL/LC_MESSAGES
rmdir themes/hybrid/locale/nl_NL
rm themes/hybrid/locale/it_IT/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/it_IT/LC_MESSAGES
rmdir themes/hybrid/locale/it_IT
rm themes/hybrid/locale/is_IS/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/is_IS/LC_MESSAGES
rmdir themes/hybrid/locale/is_IS
rm themes/hybrid/locale/fr_FR/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/fr_FR/LC_MESSAGES
rmdir themes/hybrid/locale/fr_FR
rm themes/hybrid/locale/de_DE/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/de_DE/LC_MESSAGES
rmdir themes/hybrid/locale/de_DE
rm themes/hybrid/locale/da_DK/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/da_DK/LC_MESSAGES
rmdir themes/hybrid/locale/da_DK
rm themes/hybrid/locale/cs_CZ/LC_MESSAGES/themes_hybrid.mo
rmdir themes/hybrid/locale/cs_CZ/LC_MESSAGES
rmdir themes/hybrid/locale/cs_CZ
rm themes/classic/po/vi_VN.po
rm themes/classic/po/tr_TR.po
rm themes/classic/po/sv_SE.po
rm themes/classic/po/sr_YU.po
rm themes/classic/po/ru_RU.po
rm themes/classic/po/pt_PT.po
rm themes/classic/po/pl_PL.po
rm themes/classic/po/no_NO.po
rm themes/classic/po/nl_NL.po
rm themes/classic/po/ja_JP.po
rm themes/classic/po/it_IT.po
rm themes/classic/po/is_IS.po
rm themes/classic/po/hu_HU.po
rm themes/classic/po/he_IL.po
rm themes/classic/po/ga_IE.po
rm themes/classic/po/fr_FR.po
rm themes/classic/po/fi_FI.po
rm themes/classic/po/el_GR.po
rm themes/classic/po/de_DE.po
rm themes/classic/po/da_DK.po
rm themes/classic/po/cs_CZ.po
rm themes/classic/locale/vi_VN/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/vi_VN/LC_MESSAGES
rmdir themes/classic/locale/vi_VN
rm themes/classic/locale/tr_TR/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/tr_TR/LC_MESSAGES
rmdir themes/classic/locale/tr_TR
rm themes/classic/locale/sv_SE/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/sv_SE/LC_MESSAGES
rmdir themes/classic/locale/sv_SE
rm themes/classic/locale/sr_YU/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/sr_YU/LC_MESSAGES
rmdir themes/classic/locale/sr_YU
rm themes/classic/locale/ru_RU/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/ru_RU/LC_MESSAGES
rmdir themes/classic/locale/ru_RU
rm themes/classic/locale/pt_PT/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/pt_PT/LC_MESSAGES
rmdir themes/classic/locale/pt_PT
rm themes/classic/locale/pl_PL/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/pl_PL/LC_MESSAGES
rmdir themes/classic/locale/pl_PL
rm themes/classic/locale/no_NO/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/no_NO/LC_MESSAGES
rmdir themes/classic/locale/no_NO
rm themes/classic/locale/nl_NL/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/nl_NL/LC_MESSAGES
rmdir themes/classic/locale/nl_NL
rm themes/classic/locale/ja_JP/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/ja_JP/LC_MESSAGES
rmdir themes/classic/locale/ja_JP
rm themes/classic/locale/it_IT/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/it_IT/LC_MESSAGES
rmdir themes/classic/locale/it_IT
rm themes/classic/locale/is_IS/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/is_IS/LC_MESSAGES
rmdir themes/classic/locale/is_IS
rm themes/classic/locale/hu_HU/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/hu_HU/LC_MESSAGES
rmdir themes/classic/locale/hu_HU
rm themes/classic/locale/he_IL/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/he_IL/LC_MESSAGES
rmdir themes/classic/locale/he_IL
rm themes/classic/locale/ga_IE/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/ga_IE/LC_MESSAGES
rmdir themes/classic/locale/ga_IE
rm themes/classic/locale/fr_FR/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/fr_FR/LC_MESSAGES
rmdir themes/classic/locale/fr_FR
rm themes/classic/locale/fi_FI/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/fi_FI/LC_MESSAGES
rmdir themes/classic/locale/fi_FI
rm themes/classic/locale/el_GR/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/el_GR/LC_MESSAGES
rmdir themes/classic/locale/el_GR
rm themes/classic/locale/de_DE/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/de_DE/LC_MESSAGES
rmdir themes/classic/locale/de_DE
rm themes/classic/locale/da_DK/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/da_DK/LC_MESSAGES
rmdir themes/classic/locale/da_DK
rm themes/classic/locale/cs_CZ/LC_MESSAGES/themes_classic.mo
rmdir themes/classic/locale/cs_CZ/LC_MESSAGES
rmdir themes/classic/locale/cs_CZ
rm modules/slideshow/po/vi_VN.po
rm modules/slideshow/po/tr_TR.po
rm modules/slideshow/po/sv_SE.po
rm modules/slideshow/po/sr_YU.po
rm modules/slideshow/po/ru_RU.po
rm modules/slideshow/po/pl_PL.po
rm modules/slideshow/po/no_NO.po
rm modules/slideshow/po/nl_NL.po
rm modules/slideshow/po/ja_JP.po
rm modules/slideshow/po/is_IS.po
rm modules/slideshow/po/hu_HU.po
rm modules/slideshow/po/fr_FR.po
rm modules/slideshow/po/de_DE.po
rm modules/slideshow/po/da_DK.po
rm modules/slideshow/po/cs_CZ.po
rm modules/slideshow/po/bg_BG.po
rm modules/slideshow/locale/vi_VN/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/vi_VN/LC_MESSAGES
rmdir modules/slideshow/locale/vi_VN
rm modules/slideshow/locale/tr_TR/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/tr_TR/LC_MESSAGES
rmdir modules/slideshow/locale/tr_TR
rm modules/slideshow/locale/sv_SE/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/sv_SE/LC_MESSAGES
rmdir modules/slideshow/locale/sv_SE
rm modules/slideshow/locale/sr_YU/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/sr_YU/LC_MESSAGES
rmdir modules/slideshow/locale/sr_YU
rm modules/slideshow/locale/ru_RU/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/ru_RU/LC_MESSAGES
rmdir modules/slideshow/locale/ru_RU
rm modules/slideshow/locale/pl_PL/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/pl_PL/LC_MESSAGES
rmdir modules/slideshow/locale/pl_PL
rm modules/slideshow/locale/no_NO/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/no_NO/LC_MESSAGES
rmdir modules/slideshow/locale/no_NO
rm modules/slideshow/locale/nl_NL/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/nl_NL/LC_MESSAGES
rmdir modules/slideshow/locale/nl_NL
rm modules/slideshow/locale/ja_JP/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/ja_JP/LC_MESSAGES
rmdir modules/slideshow/locale/ja_JP
rm modules/slideshow/locale/is_IS/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/is_IS/LC_MESSAGES
rmdir modules/slideshow/locale/is_IS
rm modules/slideshow/locale/hu_HU/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/hu_HU/LC_MESSAGES
rmdir modules/slideshow/locale/hu_HU
rm modules/slideshow/locale/fr_FR/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/fr_FR/LC_MESSAGES
rmdir modules/slideshow/locale/fr_FR
rm modules/slideshow/locale/de_DE/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/de_DE/LC_MESSAGES
rmdir modules/slideshow/locale/de_DE
rm modules/slideshow/locale/da_DK/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/da_DK/LC_MESSAGES
rmdir modules/slideshow/locale/da_DK
rm modules/slideshow/locale/cs_CZ/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/cs_CZ/LC_MESSAGES
rmdir modules/slideshow/locale/cs_CZ
rm modules/slideshow/locale/bg_BG/LC_MESSAGES/modules_slideshow.mo
rmdir modules/slideshow/locale/bg_BG/LC_MESSAGES
rmdir modules/slideshow/locale/bg_BG
rm modules/shutterfly/po/tr_TR.po
rm modules/shutterfly/po/sr_YU.po
rm modules/shutterfly/po/ru_RU.po
rm modules/shutterfly/po/nl_NL.po
rm modules/shutterfly/po/is_IS.po
rm modules/shutterfly/po/fr_FR.po
rm modules/shutterfly/po/de_DE.po
rm modules/shutterfly/po/cs_CZ.po
rm modules/shutterfly/locale/tr_TR/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/tr_TR/LC_MESSAGES
rmdir modules/shutterfly/locale/tr_TR
rm modules/shutterfly/locale/sr_YU/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/sr_YU/LC_MESSAGES
rmdir modules/shutterfly/locale/sr_YU
rm modules/shutterfly/locale/ru_RU/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/ru_RU/LC_MESSAGES
rmdir modules/shutterfly/locale/ru_RU
rm modules/shutterfly/locale/nl_NL/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/nl_NL/LC_MESSAGES
rmdir modules/shutterfly/locale/nl_NL
rm modules/shutterfly/locale/is_IS/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/is_IS/LC_MESSAGES
rmdir modules/shutterfly/locale/is_IS
rm modules/shutterfly/locale/fr_FR/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/fr_FR/LC_MESSAGES
rmdir modules/shutterfly/locale/fr_FR
rm modules/shutterfly/locale/de_DE/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/de_DE/LC_MESSAGES
rmdir modules/shutterfly/locale/de_DE
rm modules/shutterfly/locale/cs_CZ/LC_MESSAGES/modules_shutterfly.mo
rmdir modules/shutterfly/locale/cs_CZ/LC_MESSAGES
rmdir modules/shutterfly/locale/cs_CZ
rm modules/search/po/vi_VN.po
rm modules/search/po/tr_TR.po
rm modules/search/po/sv_SE.po
rm modules/search/po/sr_YU.po
rm modules/search/po/ru_RU.po
rm modules/search/po/pt_PT.po
rm modules/search/po/pl_PL.po
rm modules/search/po/no_NO.po
rm modules/search/po/nl_NL.po
rm modules/search/po/ja_JP.po
rm modules/search/po/is_IS.po
rm modules/search/po/hu_HU.po
rm modules/search/po/ga_IE.po
rm modules/search/po/fr_FR.po
rm modules/search/po/fi_FI.po
rm modules/search/po/de_DE.po
rm modules/search/po/da_DK.po
rm modules/search/po/cs_CZ.po
rm modules/search/po/bg_BG.po
rm modules/search/po/ar_SA.po
rm modules/search/locale/vi_VN/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/vi_VN/LC_MESSAGES
rmdir modules/search/locale/vi_VN
rm modules/search/locale/tr_TR/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/tr_TR/LC_MESSAGES
rmdir modules/search/locale/tr_TR
rm modules/search/locale/sv_SE/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/sv_SE/LC_MESSAGES
rmdir modules/search/locale/sv_SE
rm modules/search/locale/sr_YU/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/sr_YU/LC_MESSAGES
rmdir modules/search/locale/sr_YU
rm modules/search/locale/ru_RU/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/ru_RU/LC_MESSAGES
rmdir modules/search/locale/ru_RU
rm modules/search/locale/pt_PT/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/pt_PT/LC_MESSAGES
rmdir modules/search/locale/pt_PT
rm modules/search/locale/pl_PL/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/pl_PL/LC_MESSAGES
rmdir modules/search/locale/pl_PL
rm modules/search/locale/no_NO/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/no_NO/LC_MESSAGES
rmdir modules/search/locale/no_NO
rm modules/search/locale/nl_NL/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/nl_NL/LC_MESSAGES
rmdir modules/search/locale/nl_NL
rm modules/search/locale/ja_JP/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/ja_JP/LC_MESSAGES
rmdir modules/search/locale/ja_JP
rm modules/search/locale/is_IS/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/is_IS/LC_MESSAGES
rmdir modules/search/locale/is_IS
rm modules/search/locale/hu_HU/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/hu_HU/LC_MESSAGES
rmdir modules/search/locale/hu_HU
rm modules/search/locale/ga_IE/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/ga_IE/LC_MESSAGES
rmdir modules/search/locale/ga_IE
rm modules/search/locale/fr_FR/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/fr_FR/LC_MESSAGES
rmdir modules/search/locale/fr_FR
rm modules/search/locale/fi_FI/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/fi_FI/LC_MESSAGES
rmdir modules/search/locale/fi_FI
rm modules/search/locale/de_DE/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/de_DE/LC_MESSAGES
rmdir modules/search/locale/de_DE
rm modules/search/locale/da_DK/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/da_DK/LC_MESSAGES
rmdir modules/search/locale/da_DK
rm modules/search/locale/cs_CZ/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/cs_CZ/LC_MESSAGES
rmdir modules/search/locale/cs_CZ
rm modules/search/locale/bg_BG/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/bg_BG/LC_MESSAGES
rmdir modules/search/locale/bg_BG
rm modules/search/locale/ar_SA/LC_MESSAGES/modules_search.mo
rmdir modules/search/locale/ar_SA/LC_MESSAGES
rmdir modules/search/locale/ar_SA
rm modules/rewrite/templates/Troubleshooting.tpl
rm modules/rewrite/po/tr_TR.po
rm modules/rewrite/po/sv_SE.po
rm modules/rewrite/po/sr_YU.po
rm modules/rewrite/po/ru_RU.po
rm modules/rewrite/po/nl_NL.po
rm modules/rewrite/po/fr_FR.po
rm modules/rewrite/po/de_DE.po
rm modules/rewrite/po/da_DK.po
rm modules/rewrite/po/cs_CZ.po
rm modules/rewrite/locale/tr_TR/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/tr_TR/LC_MESSAGES
rmdir modules/rewrite/locale/tr_TR
rm modules/rewrite/locale/sv_SE/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/sv_SE/LC_MESSAGES
rmdir modules/rewrite/locale/sv_SE
rm modules/rewrite/locale/sr_YU/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/sr_YU/LC_MESSAGES
rmdir modules/rewrite/locale/sr_YU
rm modules/rewrite/locale/ru_RU/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/ru_RU/LC_MESSAGES
rmdir modules/rewrite/locale/ru_RU
rm modules/rewrite/locale/nl_NL/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/nl_NL/LC_MESSAGES
rmdir modules/rewrite/locale/nl_NL
rm modules/rewrite/locale/fr_FR/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/fr_FR/LC_MESSAGES
rmdir modules/rewrite/locale/fr_FR
rm modules/rewrite/locale/de_DE/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/de_DE/LC_MESSAGES
rmdir modules/rewrite/locale/de_DE
rm modules/rewrite/locale/da_DK/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/da_DK/LC_MESSAGES
rmdir modules/rewrite/locale/da_DK
rm modules/rewrite/locale/cs_CZ/LC_MESSAGES/modules_rewrite.mo
rmdir modules/rewrite/locale/cs_CZ/LC_MESSAGES
rmdir modules/rewrite/locale/cs_CZ
rm modules/rewrite/classes/interfaces/RewriteMap.inc
rm modules/rewrite/classes/interfaces/GNUmakefile
rmdir modules/rewrite/classes/interfaces
rm modules/rewrite/classes/RewriteMap.class
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/xml-src/GNUmakefile
rmdir modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/xml-src
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/RewriteMap.sql
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GNUmakefile
rmdir modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/RewriteMap.sql
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GNUmakefile
rmdir modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/RewriteMap.sql
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GNUmakefile
rmdir modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform/GNUmakefile
rmdir modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/platform
rm modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema/GNUmakefile
rmdir modules/rewrite/classes/GalleryStorage/DatabaseStorage/schema
rmdir modules/rewrite/classes/GalleryStorage/DatabaseStorage
rm modules/rearrange/po/vi_VN.po
rm modules/rearrange/po/tr_TR.po
rm modules/rearrange/po/sv_SE.po
rm modules/rearrange/po/sr_YU.po
rm modules/rearrange/po/ru_RU.po
rm modules/rearrange/po/nl_NL.po
rm modules/rearrange/po/is_IS.po
rm modules/rearrange/po/hu_HU.po
rm modules/rearrange/po/fr_FR.po
rm modules/rearrange/po/de_DE.po
rm modules/rearrange/po/cs_CZ.po
rm modules/rearrange/po/bg_BG.po
rm modules/rearrange/locale/vi_VN/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/vi_VN/LC_MESSAGES
rmdir modules/rearrange/locale/vi_VN
rm modules/rearrange/locale/tr_TR/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/tr_TR/LC_MESSAGES
rmdir modules/rearrange/locale/tr_TR
rm modules/rearrange/locale/sv_SE/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/sv_SE/LC_MESSAGES
rmdir modules/rearrange/locale/sv_SE
rm modules/rearrange/locale/sr_YU/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/sr_YU/LC_MESSAGES
rmdir modules/rearrange/locale/sr_YU
rm modules/rearrange/locale/ru_RU/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/ru_RU/LC_MESSAGES
rmdir modules/rearrange/locale/ru_RU
rm modules/rearrange/locale/nl_NL/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/nl_NL/LC_MESSAGES
rmdir modules/rearrange/locale/nl_NL
rm modules/rearrange/locale/is_IS/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/is_IS/LC_MESSAGES
rmdir modules/rearrange/locale/is_IS
rm modules/rearrange/locale/hu_HU/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/hu_HU/LC_MESSAGES
rmdir modules/rearrange/locale/hu_HU
rm modules/rearrange/locale/fr_FR/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/fr_FR/LC_MESSAGES
rmdir modules/rearrange/locale/fr_FR
rm modules/rearrange/locale/de_DE/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/de_DE/LC_MESSAGES
rmdir modules/rearrange/locale/de_DE
rm modules/rearrange/locale/cs_CZ/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/cs_CZ/LC_MESSAGES
rmdir modules/rearrange/locale/cs_CZ
rm modules/rearrange/locale/bg_BG/LC_MESSAGES/modules_rearrange.mo
rmdir modules/rearrange/locale/bg_BG/LC_MESSAGES
rmdir modules/rearrange/locale/bg_BG
rm modules/netpbm/po/vi_VN.po
rm modules/netpbm/po/tr_TR.po
rm modules/netpbm/po/sv_SE.po
rm modules/netpbm/po/sr_YU.po
rm modules/netpbm/po/ru_RU.po
rm modules/netpbm/po/pt_PT.po
rm modules/netpbm/po/pl_PL.po
rm modules/netpbm/po/no_NO.po
rm modules/netpbm/po/nl_NL.po
rm modules/netpbm/po/ja_JP.po
rm modules/netpbm/po/is_IS.po
rm modules/netpbm/po/he_IL.po
rm modules/netpbm/po/ga_IE.po
rm modules/netpbm/po/fr_FR.po
rm modules/netpbm/po/fi_FI.po
rm modules/netpbm/po/el_GR.po
rm modules/netpbm/po/de_DE.po
rm modules/netpbm/po/da_DK.po
rm modules/netpbm/po/cs_CZ.po
rm modules/netpbm/locale/vi_VN/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/vi_VN/LC_MESSAGES
rmdir modules/netpbm/locale/vi_VN
rm modules/netpbm/locale/tr_TR/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/tr_TR/LC_MESSAGES
rmdir modules/netpbm/locale/tr_TR
rm modules/netpbm/locale/sv_SE/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/sv_SE/LC_MESSAGES
rmdir modules/netpbm/locale/sv_SE
rm modules/netpbm/locale/sr_YU/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/sr_YU/LC_MESSAGES
rmdir modules/netpbm/locale/sr_YU
rm modules/netpbm/locale/ru_RU/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/ru_RU/LC_MESSAGES
rmdir modules/netpbm/locale/ru_RU
rm modules/netpbm/locale/pt_PT/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/pt_PT/LC_MESSAGES
rmdir modules/netpbm/locale/pt_PT
rm modules/netpbm/locale/pl_PL/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/pl_PL/LC_MESSAGES
rmdir modules/netpbm/locale/pl_PL
rm modules/netpbm/locale/no_NO/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/no_NO/LC_MESSAGES
rmdir modules/netpbm/locale/no_NO
rm modules/netpbm/locale/nl_NL/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/nl_NL/LC_MESSAGES
rmdir modules/netpbm/locale/nl_NL
rm modules/netpbm/locale/ja_JP/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/ja_JP/LC_MESSAGES
rmdir modules/netpbm/locale/ja_JP
rm modules/netpbm/locale/is_IS/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/is_IS/LC_MESSAGES
rmdir modules/netpbm/locale/is_IS
rm modules/netpbm/locale/he_IL/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/he_IL/LC_MESSAGES
rmdir modules/netpbm/locale/he_IL
rm modules/netpbm/locale/ga_IE/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/ga_IE/LC_MESSAGES
rmdir modules/netpbm/locale/ga_IE
rm modules/netpbm/locale/fr_FR/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/fr_FR/LC_MESSAGES
rmdir modules/netpbm/locale/fr_FR
rm modules/netpbm/locale/fi_FI/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/fi_FI/LC_MESSAGES
rmdir modules/netpbm/locale/fi_FI
rm modules/netpbm/locale/el_GR/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/el_GR/LC_MESSAGES
rmdir modules/netpbm/locale/el_GR
rm modules/netpbm/locale/de_DE/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/de_DE/LC_MESSAGES
rmdir modules/netpbm/locale/de_DE
rm modules/netpbm/locale/da_DK/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/da_DK/LC_MESSAGES
rmdir modules/netpbm/locale/da_DK
rm modules/netpbm/locale/cs_CZ/LC_MESSAGES/modules_netpbm.mo
rmdir modules/netpbm/locale/cs_CZ/LC_MESSAGES
rmdir modules/netpbm/locale/cs_CZ
rm modules/migrate/po/tr_TR.po
rm modules/migrate/po/sv_SE.po
rm modules/migrate/po/sr_YU.po
rm modules/migrate/po/ru_RU.po
rm modules/migrate/po/pt_PT.po
rm modules/migrate/po/no_NO.po
rm modules/migrate/po/nl_NL.po
rm modules/migrate/po/ja_JP.po
rm modules/migrate/po/it_IT.po
rm modules/migrate/po/is_IS.po
rm modules/migrate/po/ga_IE.po
rm modules/migrate/po/fr_FR.po
rm modules/migrate/po/fi_FI.po
rm modules/migrate/po/de_DE.po
rm modules/migrate/po/cs_CZ.po
rm modules/migrate/locale/tr_TR/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/tr_TR/LC_MESSAGES
rmdir modules/migrate/locale/tr_TR
rm modules/migrate/locale/sv_SE/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/sv_SE/LC_MESSAGES
rmdir modules/migrate/locale/sv_SE
rm modules/migrate/locale/sr_YU/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/sr_YU/LC_MESSAGES
rmdir modules/migrate/locale/sr_YU
rm modules/migrate/locale/ru_RU/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/ru_RU/LC_MESSAGES
rmdir modules/migrate/locale/ru_RU
rm modules/migrate/locale/pt_PT/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/pt_PT/LC_MESSAGES
rmdir modules/migrate/locale/pt_PT
rm modules/migrate/locale/no_NO/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/no_NO/LC_MESSAGES
rmdir modules/migrate/locale/no_NO
rm modules/migrate/locale/nl_NL/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/nl_NL/LC_MESSAGES
rmdir modules/migrate/locale/nl_NL
rm modules/migrate/locale/ja_JP/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/ja_JP/LC_MESSAGES
rmdir modules/migrate/locale/ja_JP
rm modules/migrate/locale/it_IT/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/it_IT/LC_MESSAGES
rmdir modules/migrate/locale/it_IT
rm modules/migrate/locale/is_IS/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/is_IS/LC_MESSAGES
rmdir modules/migrate/locale/is_IS
rm modules/migrate/locale/ga_IE/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/ga_IE/LC_MESSAGES
rmdir modules/migrate/locale/ga_IE
rm modules/migrate/locale/fr_FR/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/fr_FR/LC_MESSAGES
rmdir modules/migrate/locale/fr_FR
rm modules/migrate/locale/fi_FI/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/fi_FI/LC_MESSAGES
rmdir modules/migrate/locale/fi_FI
rm modules/migrate/locale/de_DE/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/de_DE/LC_MESSAGES
rmdir modules/migrate/locale/de_DE
rm modules/migrate/locale/cs_CZ/LC_MESSAGES/modules_migrate.mo
rmdir modules/migrate/locale/cs_CZ/LC_MESSAGES
rmdir modules/migrate/locale/cs_CZ
rm modules/migrate/classes/interfaces/GNUmakefile
rm modules/migrate/classes/interfaces/G1MigrateMap.inc
rmdir modules/migrate/classes/interfaces
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/xml-src/GNUmakefile
rmdir modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/xml-src
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GNUmakefile
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/G1MigrateMap.sql
rmdir modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GNUmakefile
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/G1MigrateMap.sql
rmdir modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GNUmakefile
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/G1MigrateMap.sql
rmdir modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform/GNUmakefile
rmdir modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/platform
rm modules/migrate/classes/GalleryStorage/DatabaseStorage/schema/GNUmakefile
rmdir modules/migrate/classes/GalleryStorage/DatabaseStorage/schema
rmdir modules/migrate/classes/GalleryStorage/DatabaseStorage
rm modules/migrate/classes/G1MigrateMap.class
rm modules/imagemagick/po/vi_VN.po
rm modules/imagemagick/po/tr_TR.po
rm modules/imagemagick/po/sv_SE.po
rm modules/imagemagick/po/sr_YU.po
rm modules/imagemagick/po/ru_RU.po
rm modules/imagemagick/po/pt_PT.po
rm modules/imagemagick/po/pl_PL.po
rm modules/imagemagick/po/no_NO.po
rm modules/imagemagick/po/nl_NL.po
rm modules/imagemagick/po/ja_JP.po
rm modules/imagemagick/po/it_IT.po
rm modules/imagemagick/po/is_IS.po
rm modules/imagemagick/po/ga_IE.po
rm modules/imagemagick/po/fr_FR.po
rm modules/imagemagick/po/fi_FI.po
rm modules/imagemagick/po/el_GR.po
rm modules/imagemagick/po/de_DE.po
rm modules/imagemagick/po/da_DK.po
rm modules/imagemagick/po/cs_CZ.po
rm modules/imagemagick/locale/vi_VN/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/vi_VN/LC_MESSAGES
rmdir modules/imagemagick/locale/vi_VN
rm modules/imagemagick/locale/tr_TR/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/tr_TR/LC_MESSAGES
rmdir modules/imagemagick/locale/tr_TR
rm modules/imagemagick/locale/sv_SE/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/sv_SE/LC_MESSAGES
rmdir modules/imagemagick/locale/sv_SE
rm modules/imagemagick/locale/sr_YU/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/sr_YU/LC_MESSAGES
rmdir modules/imagemagick/locale/sr_YU
rm modules/imagemagick/locale/ru_RU/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/ru_RU/LC_MESSAGES
rmdir modules/imagemagick/locale/ru_RU
rm modules/imagemagick/locale/pt_PT/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/pt_PT/LC_MESSAGES
rmdir modules/imagemagick/locale/pt_PT
rm modules/imagemagick/locale/pl_PL/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/pl_PL/LC_MESSAGES
rmdir modules/imagemagick/locale/pl_PL
rm modules/imagemagick/locale/no_NO/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/no_NO/LC_MESSAGES
rmdir modules/imagemagick/locale/no_NO
rm modules/imagemagick/locale/nl_NL/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/nl_NL/LC_MESSAGES
rmdir modules/imagemagick/locale/nl_NL
rm modules/imagemagick/locale/ja_JP/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/ja_JP/LC_MESSAGES
rmdir modules/imagemagick/locale/ja_JP
rm modules/imagemagick/locale/it_IT/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/it_IT/LC_MESSAGES
rmdir modules/imagemagick/locale/it_IT
rm modules/imagemagick/locale/is_IS/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/is_IS/LC_MESSAGES
rmdir modules/imagemagick/locale/is_IS
rm modules/imagemagick/locale/ga_IE/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/ga_IE/LC_MESSAGES
rmdir modules/imagemagick/locale/ga_IE
rm modules/imagemagick/locale/fr_FR/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/fr_FR/LC_MESSAGES
rmdir modules/imagemagick/locale/fr_FR
rm modules/imagemagick/locale/fi_FI/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/fi_FI/LC_MESSAGES
rmdir modules/imagemagick/locale/fi_FI
rm modules/imagemagick/locale/el_GR/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/el_GR/LC_MESSAGES
rmdir modules/imagemagick/locale/el_GR
rm modules/imagemagick/locale/de_DE/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/de_DE/LC_MESSAGES
rmdir modules/imagemagick/locale/de_DE
rm modules/imagemagick/locale/da_DK/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/da_DK/LC_MESSAGES
rmdir modules/imagemagick/locale/da_DK
rm modules/imagemagick/locale/cs_CZ/LC_MESSAGES/modules_imagemagick.mo
rmdir modules/imagemagick/locale/cs_CZ/LC_MESSAGES
rmdir modules/imagemagick/locale/cs_CZ
rm modules/icons/po/tr_TR.po
rm modules/icons/po/sv_SE.po
rm modules/icons/po/sr_YU.po
rm modules/icons/po/ru_RU.po
rm modules/icons/po/nl_NL.po
rm modules/icons/po/it_IT.po
rm modules/icons/po/fr_FR.po
rm modules/icons/po/de_DE.po
rm modules/icons/po/da_DK.po
rm modules/icons/po/cs_CZ.po
rm modules/icons/po/bg_BG.po
rm modules/icons/locale/tr_TR/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/tr_TR/LC_MESSAGES
rmdir modules/icons/locale/tr_TR
rm modules/icons/locale/sv_SE/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/sv_SE/LC_MESSAGES
rmdir modules/icons/locale/sv_SE
rm modules/icons/locale/sr_YU/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/sr_YU/LC_MESSAGES
rmdir modules/icons/locale/sr_YU
rm modules/icons/locale/ru_RU/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/ru_RU/LC_MESSAGES
rmdir modules/icons/locale/ru_RU
rm modules/icons/locale/nl_NL/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/nl_NL/LC_MESSAGES
rmdir modules/icons/locale/nl_NL
rm modules/icons/locale/it_IT/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/it_IT/LC_MESSAGES
rmdir modules/icons/locale/it_IT
rm modules/icons/locale/fr_FR/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/fr_FR/LC_MESSAGES
rmdir modules/icons/locale/fr_FR
rm modules/icons/locale/de_DE/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/de_DE/LC_MESSAGES
rmdir modules/icons/locale/de_DE
rm modules/icons/locale/da_DK/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/da_DK/LC_MESSAGES
rmdir modules/icons/locale/da_DK
rm modules/icons/locale/cs_CZ/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/cs_CZ/LC_MESSAGES
rmdir modules/icons/locale/cs_CZ
rm modules/icons/locale/bg_BG/LC_MESSAGES/modules_icons.mo
rmdir modules/icons/locale/bg_BG/LC_MESSAGES
rmdir modules/icons/locale/bg_BG
rm modules/gd/po/vi_VN.po
rm modules/gd/po/tr_TR.po
rm modules/gd/po/sr_YU.po
rm modules/gd/po/ru_RU.po
rm modules/gd/po/pl_PL.po
rm modules/gd/po/no_NO.po
rm modules/gd/po/nl_NL.po
rm modules/gd/po/it_IT.po
rm modules/gd/po/is_IS.po
rm modules/gd/po/fr_FR.po
rm modules/gd/po/de_DE.po
rm modules/gd/po/da_DK.po
rm modules/gd/po/cs_CZ.po
rm modules/gd/locale/vi_VN/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/vi_VN/LC_MESSAGES
rmdir modules/gd/locale/vi_VN
rm modules/gd/locale/tr_TR/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/tr_TR/LC_MESSAGES
rmdir modules/gd/locale/tr_TR
rm modules/gd/locale/sr_YU/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/sr_YU/LC_MESSAGES
rmdir modules/gd/locale/sr_YU
rm modules/gd/locale/ru_RU/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/ru_RU/LC_MESSAGES
rmdir modules/gd/locale/ru_RU
rm modules/gd/locale/pl_PL/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/pl_PL/LC_MESSAGES
rmdir modules/gd/locale/pl_PL
rm modules/gd/locale/no_NO/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/no_NO/LC_MESSAGES
rmdir modules/gd/locale/no_NO
rm modules/gd/locale/nl_NL/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/nl_NL/LC_MESSAGES
rmdir modules/gd/locale/nl_NL
rm modules/gd/locale/it_IT/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/it_IT/LC_MESSAGES
rmdir modules/gd/locale/it_IT
rm modules/gd/locale/is_IS/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/is_IS/LC_MESSAGES
rmdir modules/gd/locale/is_IS
rm modules/gd/locale/fr_FR/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/fr_FR/LC_MESSAGES
rmdir modules/gd/locale/fr_FR
rm modules/gd/locale/de_DE/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/de_DE/LC_MESSAGES
rmdir modules/gd/locale/de_DE
rm modules/gd/locale/da_DK/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/da_DK/LC_MESSAGES
rmdir modules/gd/locale/da_DK
rm modules/gd/locale/cs_CZ/LC_MESSAGES/modules_gd.mo
rmdir modules/gd/locale/cs_CZ/LC_MESSAGES
rmdir modules/gd/locale/cs_CZ
rm modules/ffmpeg/po/vi_VN.po
rm modules/ffmpeg/po/tr_TR.po
rm modules/ffmpeg/po/sv_SE.po
rm modules/ffmpeg/po/sr_YU.po
rm modules/ffmpeg/po/ru_RU.po
rm modules/ffmpeg/po/pt_PT.po
rm modules/ffmpeg/po/no_NO.po
rm modules/ffmpeg/po/nl_NL.po
rm modules/ffmpeg/po/ja_JP.po
rm modules/ffmpeg/po/it_IT.po
rm modules/ffmpeg/po/is_IS.po
rm modules/ffmpeg/po/ga_IE.po
rm modules/ffmpeg/po/fr_FR.po
rm modules/ffmpeg/po/de_DE.po
rm modules/ffmpeg/po/da_DK.po
rm modules/ffmpeg/po/cs_CZ.po
rm modules/ffmpeg/locale/vi_VN/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/vi_VN/LC_MESSAGES
rmdir modules/ffmpeg/locale/vi_VN
rm modules/ffmpeg/locale/tr_TR/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/tr_TR/LC_MESSAGES
rmdir modules/ffmpeg/locale/tr_TR
rm modules/ffmpeg/locale/sv_SE/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/sv_SE/LC_MESSAGES
rmdir modules/ffmpeg/locale/sv_SE
rm modules/ffmpeg/locale/sr_YU/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/sr_YU/LC_MESSAGES
rmdir modules/ffmpeg/locale/sr_YU
rm modules/ffmpeg/locale/ru_RU/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/ru_RU/LC_MESSAGES
rmdir modules/ffmpeg/locale/ru_RU
rm modules/ffmpeg/locale/pt_PT/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/pt_PT/LC_MESSAGES
rmdir modules/ffmpeg/locale/pt_PT
rm modules/ffmpeg/locale/no_NO/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/no_NO/LC_MESSAGES
rmdir modules/ffmpeg/locale/no_NO
rm modules/ffmpeg/locale/nl_NL/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/nl_NL/LC_MESSAGES
rmdir modules/ffmpeg/locale/nl_NL
rm modules/ffmpeg/locale/ja_JP/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/ja_JP/LC_MESSAGES
rmdir modules/ffmpeg/locale/ja_JP
rm modules/ffmpeg/locale/it_IT/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/it_IT/LC_MESSAGES
rmdir modules/ffmpeg/locale/it_IT
rm modules/ffmpeg/locale/is_IS/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/is_IS/LC_MESSAGES
rmdir modules/ffmpeg/locale/is_IS
rm modules/ffmpeg/locale/ga_IE/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/ga_IE/LC_MESSAGES
rmdir modules/ffmpeg/locale/ga_IE
rm modules/ffmpeg/locale/fr_FR/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/fr_FR/LC_MESSAGES
rmdir modules/ffmpeg/locale/fr_FR
rm modules/ffmpeg/locale/de_DE/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/de_DE/LC_MESSAGES
rmdir modules/ffmpeg/locale/de_DE
rm modules/ffmpeg/locale/da_DK/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/da_DK/LC_MESSAGES
rmdir modules/ffmpeg/locale/da_DK
rm modules/ffmpeg/locale/cs_CZ/LC_MESSAGES/modules_ffmpeg.mo
rmdir modules/ffmpeg/locale/cs_CZ/LC_MESSAGES
rmdir modules/ffmpeg/locale/cs_CZ
rm modules/exif/po/vi_VN.po
rm modules/exif/po/tr_TR.po
rm modules/exif/po/sv_SE.po
rm modules/exif/po/sr_YU.po
rm modules/exif/po/ru_RU.po
rm modules/exif/po/no_NO.po
rm modules/exif/po/nl_NL.po
rm modules/exif/po/it_IT.po
rm modules/exif/po/is_IS.po
rm modules/exif/po/ga_IE.po
rm modules/exif/po/fr_FR.po
rm modules/exif/po/de_DE.po
rm modules/exif/po/da_DK.po
rm modules/exif/po/cs_CZ.po
rm modules/exif/locale/vi_VN/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/vi_VN/LC_MESSAGES
rmdir modules/exif/locale/vi_VN
rm modules/exif/locale/tr_TR/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/tr_TR/LC_MESSAGES
rmdir modules/exif/locale/tr_TR
rm modules/exif/locale/sv_SE/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/sv_SE/LC_MESSAGES
rmdir modules/exif/locale/sv_SE
rm modules/exif/locale/sr_YU/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/sr_YU/LC_MESSAGES
rmdir modules/exif/locale/sr_YU
rm modules/exif/locale/ru_RU/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/ru_RU/LC_MESSAGES
rmdir modules/exif/locale/ru_RU
rm modules/exif/locale/no_NO/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/no_NO/LC_MESSAGES
rmdir modules/exif/locale/no_NO
rm modules/exif/locale/nl_NL/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/nl_NL/LC_MESSAGES
rmdir modules/exif/locale/nl_NL
rm modules/exif/locale/it_IT/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/it_IT/LC_MESSAGES
rmdir modules/exif/locale/it_IT
rm modules/exif/locale/is_IS/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/is_IS/LC_MESSAGES
rmdir modules/exif/locale/is_IS
rm modules/exif/locale/ga_IE/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/ga_IE/LC_MESSAGES
rmdir modules/exif/locale/ga_IE
rm modules/exif/locale/fr_FR/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/fr_FR/LC_MESSAGES
rmdir modules/exif/locale/fr_FR
rm modules/exif/locale/de_DE/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/de_DE/LC_MESSAGES
rmdir modules/exif/locale/de_DE
rm modules/exif/locale/da_DK/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/da_DK/LC_MESSAGES
rmdir modules/exif/locale/da_DK
rm modules/exif/locale/cs_CZ/LC_MESSAGES/modules_exif.mo
rmdir modules/exif/locale/cs_CZ/LC_MESSAGES
rmdir modules/exif/locale/cs_CZ
rm modules/exif/classes/interfaces/GNUmakefile
rm modules/exif/classes/interfaces/ExifPropertiesMap.inc
rmdir modules/exif/classes/interfaces
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/xml-src/GNUmakefile
rmdir modules/exif/classes/GalleryStorage/DatabaseStorage/schema/xml-src
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GNUmakefile
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/ExifPropertiesMap.sql
rmdir modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GNUmakefile
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/ExifPropertiesMap.sql
rmdir modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GNUmakefile
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/ExifPropertiesMap.sql
rmdir modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform/GNUmakefile
rmdir modules/exif/classes/GalleryStorage/DatabaseStorage/schema/platform
rm modules/exif/classes/GalleryStorage/DatabaseStorage/schema/GNUmakefile
rmdir modules/exif/classes/GalleryStorage/DatabaseStorage/schema
rmdir modules/exif/classes/GalleryStorage/DatabaseStorage
rm modules/exif/classes/ExifPropertiesMap.class
rm modules/core/templates/ShowItemHead.tpl
rm modules/core/po/vi_VN.po
rm modules/core/po/tr_TR.po
rm modules/core/po/sv_SE.po
rm modules/core/po/sr_YU.po
rm modules/core/po/ru_RU.po
rm modules/core/po/pt_PT.po
rm modules/core/po/pl_PL.po
rm modules/core/po/no_NO.po
rm modules/core/po/nl_NL.po
rm modules/core/po/ja_JP.po
rm modules/core/po/it_IT.po
rm modules/core/po/is_IS.po
rm modules/core/po/hu_HU.po
rm modules/core/po/he_IL.po
rm modules/core/po/ga_IE.po
rm modules/core/po/fr_FR.po
rm modules/core/po/fi_FI.po
rm modules/core/po/el_GR.po
rm modules/core/po/de_DE.po
rm modules/core/po/da_DK.po
rm modules/core/po/cs_CZ.po
rm modules/core/po/bg_BG.po
rm modules/core/po/ar_SA.po
rm modules/core/locale/vi_VN/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/vi_VN/LC_MESSAGES
rmdir modules/core/locale/vi_VN
rm modules/core/locale/tr_TR/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/tr_TR/LC_MESSAGES
rmdir modules/core/locale/tr_TR
rm modules/core/locale/sv_SE/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/sv_SE/LC_MESSAGES
rmdir modules/core/locale/sv_SE
rm modules/core/locale/sr_YU/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/sr_YU/LC_MESSAGES
rmdir modules/core/locale/sr_YU
rm modules/core/locale/ru_RU/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/ru_RU/LC_MESSAGES
rmdir modules/core/locale/ru_RU
rm modules/core/locale/pt_PT/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/pt_PT/LC_MESSAGES
rmdir modules/core/locale/pt_PT
rm modules/core/locale/pl_PL/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/pl_PL/LC_MESSAGES
rmdir modules/core/locale/pl_PL
rm modules/core/locale/no_NO/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/no_NO/LC_MESSAGES
rmdir modules/core/locale/no_NO
rm modules/core/locale/nl_NL/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/nl_NL/LC_MESSAGES
rmdir modules/core/locale/nl_NL
rm modules/core/locale/ja_JP/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/ja_JP/LC_MESSAGES
rmdir modules/core/locale/ja_JP
rm modules/core/locale/it_IT/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/it_IT/LC_MESSAGES
rmdir modules/core/locale/it_IT
rm modules/core/locale/is_IS/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/is_IS/LC_MESSAGES
rmdir modules/core/locale/is_IS
rm modules/core/locale/hu_HU/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/hu_HU/LC_MESSAGES
rmdir modules/core/locale/hu_HU
rm modules/core/locale/he_IL/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/he_IL/LC_MESSAGES
rmdir modules/core/locale/he_IL
rm modules/core/locale/ga_IE/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/ga_IE/LC_MESSAGES
rmdir modules/core/locale/ga_IE
rm modules/core/locale/fr_FR/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/fr_FR/LC_MESSAGES
rmdir modules/core/locale/fr_FR
rm modules/core/locale/fi_FI/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/fi_FI/LC_MESSAGES
rmdir modules/core/locale/fi_FI
rm modules/core/locale/el_GR/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/el_GR/LC_MESSAGES
rmdir modules/core/locale/el_GR
rm modules/core/locale/de_DE/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/de_DE/LC_MESSAGES
rmdir modules/core/locale/de_DE
rm modules/core/locale/da_DK/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/da_DK/LC_MESSAGES
rmdir modules/core/locale/da_DK
rm modules/core/locale/cs_CZ/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/cs_CZ/LC_MESSAGES
rmdir modules/core/locale/cs_CZ
rm modules/core/locale/bg_BG/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/bg_BG/LC_MESSAGES
rmdir modules/core/locale/bg_BG
rm modules/core/locale/ar_SA/LC_MESSAGES/modules_core.mo
rmdir modules/core/locale/ar_SA/LC_MESSAGES
rmdir modules/core/locale/ar_SA
rm modules/core/data/g2-unpossible.png
rm modules/core/data/g2-unpossible.mp3
rm modules/core/classes/interfaces/GalleryUserGroupMap.inc
rm modules/core/classes/interfaces/GalleryUser.inc
rm modules/core/classes/interfaces/GalleryUnknownItem.inc
rm modules/core/classes/interfaces/GalleryToolkitPropertyMimeTypeMap.inc
rm modules/core/classes/interfaces/GalleryToolkitPropertyMap.inc
rm modules/core/classes/interfaces/GalleryToolkitOperationParameterMap.inc
rm modules/core/classes/interfaces/GalleryToolkitOperationMimeTypeMap.inc
rm modules/core/classes/interfaces/GalleryToolkitOperationMap.inc
rm modules/core/classes/interfaces/GalleryRecoverPasswordMap.inc
rm modules/core/classes/interfaces/GalleryPluginParameterMap.inc
rm modules/core/classes/interfaces/GalleryPluginMap.inc
rm modules/core/classes/interfaces/GalleryPhotoItem.inc
rm modules/core/classes/interfaces/GalleryPermissionSetMap.inc
rm modules/core/classes/interfaces/GalleryMovieItem.inc
rm modules/core/classes/interfaces/GalleryMimeTypeMap.inc
rm modules/core/classes/interfaces/GalleryMaintenanceMap.inc
rm modules/core/classes/interfaces/GalleryItemAttributesMap.inc
rm modules/core/classes/interfaces/GalleryItem.inc
rm modules/core/classes/interfaces/GalleryGroup.inc
rm modules/core/classes/interfaces/GalleryFileSystemEntity.inc
rm modules/core/classes/interfaces/GalleryFactoryMap.inc
rm modules/core/classes/interfaces/GalleryEntity.inc
rm modules/core/classes/interfaces/GalleryDescendentCountsMap.inc
rm modules/core/classes/interfaces/GalleryDerivativePreferencesMap.inc
rm modules/core/classes/interfaces/GalleryDerivativeImage.inc
rm modules/core/classes/interfaces/GalleryDerivative.inc
rm modules/core/classes/interfaces/GalleryDataItem.inc
rm modules/core/classes/interfaces/GalleryChildEntity.inc
rm modules/core/classes/interfaces/GalleryAnimationItem.inc
rm modules/core/classes/interfaces/GalleryAlbumItem.inc
rm modules/core/classes/interfaces/GalleryAccessSubscriberMap.inc
rm modules/core/classes/interfaces/GalleryAccessMap.inc
rm modules/core/classes/interfaces/GNUmakefile
rm modules/core/classes/interfaces/ExternalIdMap.inc
rm modules/core/classes/interfaces/ClassCode.xsl
rmdir modules/core/classes/interfaces
rm modules/core/classes/GalleryUserGroupMap.class
rm modules/core/classes/GalleryToolkitPropertyMimeTypeMap.class
rm modules/core/classes/GalleryToolkitPropertyMap.class
rm modules/core/classes/GalleryToolkitOperationParameterMap.class
rm modules/core/classes/GalleryToolkitOperationMimeTypeMap.class
rm modules/core/classes/GalleryToolkitOperationMap.class
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/Schema.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/R_GalleryPermissionMap_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/R_GalleryItemPropertiesMap_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/Lock.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/GNUmakefile
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/DbXml.xsl
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryPluginParameterMap_1.1.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryPluginParameterMap_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryPluginMap_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryItem_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryGroup_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryEntity_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryDerivative_1.0.xml
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src/A_GalleryAlbumItem_1.0.xml
rmdir modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-src
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-out/InstallerTest.xml
rmdir modules/core/classes/GalleryStorage/DatabaseStorage/schema/xml-out
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/Schema.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/R_GalleryPermissionMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/R_GalleryItemPropertiesMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/PostgreSQL.xsl
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/Lock.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/InstallerTest_sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryUserGroupMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryUser.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryUnknownItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryToolkitPropertyMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryToolkitPropertyMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryToolkitOperationParameterMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryToolkitOperationMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryToolkitOperationMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryRecoverPasswordMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryPluginParameterMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryPluginMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryPhotoItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryPermissionSetMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryMovieItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryMaintenanceMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryItemAttributesMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryGroup.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryFileSystemEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryFactoryMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryDescendentCountsMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryDerivativePreferencesMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryDerivativeImage.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryDerivative.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryDataItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryChildEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryAnimationItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryAlbumItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryAccessSubscriberMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryAccessMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GNUmakefile
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/ExternalIdMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryPluginParameterMap_1.1.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryPluginParameterMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryPluginMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryItem_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryGroup_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryEntity_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryDerivative_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/A_GalleryAlbumItem_1.0.sql
rmdir modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/Schema.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/R_GalleryPermissionMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/R_GalleryItemPropertiesMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/Oracle.xsl
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/Lock.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/InstallerTest_sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/InitRandom.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryUserGroupMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryUser.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryUnknownItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryToolkitPropertyMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryToolkitPropertyMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryToolkitOperationParameterMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryToolkitOperationMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryToolkitOperationMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryRecoverPasswordMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryPluginParameterMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryPluginMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryPhotoItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryPermissionSetMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryMovieItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryMaintenanceMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryItemAttributesMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryGroup.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryFileSystemEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryFactoryMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryDescendentCountsMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryDerivativePreferencesMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryDerivativeImage.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryDerivative.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryDataItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryChildEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryAnimationItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryAlbumItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryAccessSubscriberMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryAccessMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GNUmakefile
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/ExternalIdMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/CreateBitOr_sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryPluginParameterMap_1.1.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryPluginParameterMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryPluginMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryItem_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryGroup_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryEntity_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryDerivative_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/A_GalleryAlbumItem_1.0.sql
rmdir modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/Schema.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/R_GalleryPermissionMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/R_GalleryItemPropertiesMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/MySQL.xsl
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/Lock.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/InstallerTest_sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryUserGroupMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryUser.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryUnknownItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryToolkitPropertyMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryToolkitPropertyMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryToolkitOperationParameterMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryToolkitOperationMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryToolkitOperationMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryRecoverPasswordMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryPluginParameterMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryPluginMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryPhotoItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryPermissionSetMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryMovieItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryMimeTypeMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryMaintenanceMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryItemAttributesMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryGroup.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryFileSystemEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryFactoryMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryDescendentCountsMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryDerivativePreferencesMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryDerivativeImage.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryDerivative.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryDataItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryChildEntity.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryAnimationItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryAlbumItem.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryAccessSubscriberMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryAccessMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GNUmakefile
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/ExternalIdMap.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryPluginParameterMap_1.1.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryPluginParameterMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryPluginMap_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryItem_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryGroup_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryEntity_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryDerivative_1.0.sql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/A_GalleryAlbumItem_1.0.sql
rmdir modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/GNUmakefile.inc
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform/GNUmakefile
rmdir modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform
rm modules/core/classes/GalleryStorage/DatabaseStorage/schema/GNUmakefile
rmdir modules/core/classes/GalleryStorage/DatabaseStorage/schema
rm modules/core/classes/GalleryStorage/DatabaseStorage/PostgreSqlDatabaseStorage.class
rm modules/core/classes/GalleryStorage/DatabaseStorage/OracleDatabaseStorage.class
rm modules/core/classes/GalleryStorage/DatabaseStorage/MySqlDatabaseStorage.class
rm modules/core/classes/GalleryStorage/DatabaseStorage/ErrorHandler.inc
rm modules/core/classes/GalleryStorage/DatabaseStorage.class
rmdir modules/core/classes/GalleryStorage/DatabaseStorage
rm modules/core/classes/GalleryStorage/DatabaseSqlFragment.class
rm modules/core/classes/GalleryStorage/DatabaseSearchResults.class
rm modules/core/classes/GallerySearchResults.class
rm modules/core/classes/GalleryRecoverPasswordMap.class
rm modules/core/classes/GalleryPluginParameterMap.class
rm modules/core/classes/GalleryPluginMap.class
rm modules/core/classes/GalleryPermissionSetMap.class
rm modules/core/classes/GalleryMimeTypeMap.class
rm modules/core/classes/GalleryMaintenanceMap.class
rm modules/core/classes/GalleryItemAttributesMap.class
rm modules/core/classes/GalleryFactoryMap.class
rm modules/core/classes/GalleryDescendentCountsMap.class
rm modules/core/classes/GalleryDerivativePreferencesMap.class
rm modules/core/classes/GalleryAccessSubscriberMap.class
rm modules/core/classes/GalleryAccessMap.class
rm modules/core/classes/ExternalIdMap.class
rm modules/comment/po/vi_VN.po
rm modules/comment/po/tr_TR.po
rm modules/comment/po/sv_SE.po
rm modules/comment/po/sr_YU.po
rm modules/comment/po/ru_RU.po
rm modules/comment/po/pt_PT.po
rm modules/comment/po/pl_PL.po
rm modules/comment/po/no_NO.po
rm modules/comment/po/nl_NL.po
rm modules/comment/po/ja_JP.po
rm modules/comment/po/it_IT.po
rm modules/comment/po/is_IS.po
rm modules/comment/po/hu_HU.po
rm modules/comment/po/he_IL.po
rm modules/comment/po/ga_IE.po
rm modules/comment/po/fr_FR.po
rm modules/comment/po/fi_FI.po
rm modules/comment/po/el_GR.po
rm modules/comment/po/de_DE.po
rm modules/comment/po/da_DK.po
rm modules/comment/po/cs_CZ.po
rm modules/comment/po/bg_BG.po
rm modules/comment/po/ar_SA.po
rm modules/comment/locale/vi_VN/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/vi_VN/LC_MESSAGES
rmdir modules/comment/locale/vi_VN
rm modules/comment/locale/tr_TR/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/tr_TR/LC_MESSAGES
rmdir modules/comment/locale/tr_TR
rm modules/comment/locale/sv_SE/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/sv_SE/LC_MESSAGES
rmdir modules/comment/locale/sv_SE
rm modules/comment/locale/sr_YU/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/sr_YU/LC_MESSAGES
rmdir modules/comment/locale/sr_YU
rm modules/comment/locale/ru_RU/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/ru_RU/LC_MESSAGES
rmdir modules/comment/locale/ru_RU
rm modules/comment/locale/pt_PT/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/pt_PT/LC_MESSAGES
rmdir modules/comment/locale/pt_PT
rm modules/comment/locale/pl_PL/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/pl_PL/LC_MESSAGES
rmdir modules/comment/locale/pl_PL
rm modules/comment/locale/no_NO/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/no_NO/LC_MESSAGES
rmdir modules/comment/locale/no_NO
rm modules/comment/locale/nl_NL/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/nl_NL/LC_MESSAGES
rmdir modules/comment/locale/nl_NL
rm modules/comment/locale/ja_JP/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/ja_JP/LC_MESSAGES
rmdir modules/comment/locale/ja_JP
rm modules/comment/locale/it_IT/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/it_IT/LC_MESSAGES
rmdir modules/comment/locale/it_IT
rm modules/comment/locale/is_IS/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/is_IS/LC_MESSAGES
rmdir modules/comment/locale/is_IS
rm modules/comment/locale/hu_HU/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/hu_HU/LC_MESSAGES
rmdir modules/comment/locale/hu_HU
rm modules/comment/locale/he_IL/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/he_IL/LC_MESSAGES
rmdir modules/comment/locale/he_IL
rm modules/comment/locale/ga_IE/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/ga_IE/LC_MESSAGES
rmdir modules/comment/locale/ga_IE
rm modules/comment/locale/fr_FR/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/fr_FR/LC_MESSAGES
rmdir modules/comment/locale/fr_FR
rm modules/comment/locale/fi_FI/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/fi_FI/LC_MESSAGES
rmdir modules/comment/locale/fi_FI
rm modules/comment/locale/el_GR/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/el_GR/LC_MESSAGES
rmdir modules/comment/locale/el_GR
rm modules/comment/locale/de_DE/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/de_DE/LC_MESSAGES
rmdir modules/comment/locale/de_DE
rm modules/comment/locale/da_DK/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/da_DK/LC_MESSAGES
rmdir modules/comment/locale/da_DK
rm modules/comment/locale/cs_CZ/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/cs_CZ/LC_MESSAGES
rmdir modules/comment/locale/cs_CZ
rm modules/comment/locale/bg_BG/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/bg_BG/LC_MESSAGES
rmdir modules/comment/locale/bg_BG
rm modules/comment/locale/ar_SA/LC_MESSAGES/modules_comment.mo
rmdir modules/comment/locale/ar_SA/LC_MESSAGES
rmdir modules/comment/locale/ar_SA
rm modules/comment/classes/interfaces/GalleryComment.inc
rm modules/comment/classes/interfaces/GNUmakefile
rmdir modules/comment/classes/interfaces
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/xml-src/GNUmakefile
rmdir modules/comment/classes/GalleryStorage/DatabaseStorage/schema/xml-src
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GalleryComment.sql
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres/GNUmakefile
rmdir modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/postgres
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GalleryComment.sql
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle/GNUmakefile
rmdir modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/oracle
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GalleryComment.sql
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql/GNUmakefile
rmdir modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/mysql
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform/GNUmakefile
rmdir modules/comment/classes/GalleryStorage/DatabaseStorage/schema/platform
rm modules/comment/classes/GalleryStorage/DatabaseStorage/schema/GNUmakefile
rmdir modules/comment/classes/GalleryStorage/DatabaseStorage/schema
rmdir modules/comment/classes/GalleryStorage/DatabaseStorage
rm modules/archiveupload/po/vi_VN.po
rm modules/archiveupload/po/tr_TR.po
rm modules/archiveupload/po/sv_SE.po
rm modules/archiveupload/po/sr_YU.po
rm modules/archiveupload/po/ru_RU.po
rm modules/archiveupload/po/no_NO.po
rm modules/archiveupload/po/nl_NL.po
rm modules/archiveupload/po/it_IT.po
rm modules/archiveupload/po/is_IS.po
rm modules/archiveupload/po/hu_HU.po
rm modules/archiveupload/po/fr_FR.po
rm modules/archiveupload/po/de_DE.po
rm modules/archiveupload/po/da_DK.po
rm modules/archiveupload/po/cs_CZ.po
rm modules/archiveupload/po/bg_BG.po
rm modules/archiveupload/locale/vi_VN/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/vi_VN/LC_MESSAGES
rmdir modules/archiveupload/locale/vi_VN
rm modules/archiveupload/locale/tr_TR/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/tr_TR/LC_MESSAGES
rmdir modules/archiveupload/locale/tr_TR
rm modules/archiveupload/locale/sv_SE/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/sv_SE/LC_MESSAGES
rmdir modules/archiveupload/locale/sv_SE
rm modules/archiveupload/locale/sr_YU/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/sr_YU/LC_MESSAGES
rmdir modules/archiveupload/locale/sr_YU
rm modules/archiveupload/locale/ru_RU/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/ru_RU/LC_MESSAGES
rmdir modules/archiveupload/locale/ru_RU
rm modules/archiveupload/locale/no_NO/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/no_NO/LC_MESSAGES
rmdir modules/archiveupload/locale/no_NO
rm modules/archiveupload/locale/nl_NL/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/nl_NL/LC_MESSAGES
rmdir modules/archiveupload/locale/nl_NL
rm modules/archiveupload/locale/it_IT/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/it_IT/LC_MESSAGES
rmdir modules/archiveupload/locale/it_IT
rm modules/archiveupload/locale/is_IS/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/is_IS/LC_MESSAGES
rmdir modules/archiveupload/locale/is_IS
rm modules/archiveupload/locale/hu_HU/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/hu_HU/LC_MESSAGES
rmdir modules/archiveupload/locale/hu_HU
rm modules/archiveupload/locale/fr_FR/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/fr_FR/LC_MESSAGES
rmdir modules/archiveupload/locale/fr_FR
rm modules/archiveupload/locale/de_DE/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/de_DE/LC_MESSAGES
rmdir modules/archiveupload/locale/de_DE
rm modules/archiveupload/locale/da_DK/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/da_DK/LC_MESSAGES
rmdir modules/archiveupload/locale/da_DK
rm modules/archiveupload/locale/cs_CZ/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/cs_CZ/LC_MESSAGES
rmdir modules/archiveupload/locale/cs_CZ
rm modules/archiveupload/locale/bg_BG/LC_MESSAGES/modules_archiveupload.mo
rmdir modules/archiveupload/locale/bg_BG/LC_MESSAGES
rmdir modules/archiveupload/locale/bg_BG
rm install/po/vi_VN.po
rm install/po/tr_TR.po
rm install/po/sr_YU.po
rm install/po/nl_NL.po
rm install/po/ja_JP.po
rm install/po/it_IT.po
rm install/po/fr_FR.po
rm install/po/de_DE.po
rm install/po/cs_CZ.po
rm install/po/bg_BG.po
rm install/locale/vi_VN/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/vi_VN/LC_MESSAGES
rmdir install/locale/vi_VN
rm install/locale/tr_TR/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/tr_TR/LC_MESSAGES
rmdir install/locale/tr_TR
rm install/locale/sr_YU/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/sr_YU/LC_MESSAGES
rmdir install/locale/sr_YU
rm install/locale/nl_NL/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/nl_NL/LC_MESSAGES
rmdir install/locale/nl_NL
rm install/locale/ja_JP/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/ja_JP/LC_MESSAGES
rmdir install/locale/ja_JP
rm install/locale/it_IT/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/it_IT/LC_MESSAGES
rmdir install/locale/it_IT
rm install/locale/fr_FR/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/fr_FR/LC_MESSAGES
rmdir install/locale/fr_FR
rm install/locale/de_DE/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/de_DE/LC_MESSAGES
rmdir install/locale/de_DE
rm install/locale/cs_CZ/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/cs_CZ/LC_MESSAGES
rmdir install/locale/cs_CZ
rm install/locale/bg_BG/LC_MESSAGES/gallery2_install.mo
rmdir install/locale/bg_BG/LC_MESSAGES
rmdir install/locale/bg_BG
rm docs/EMBEDDING
rm docs/DEVELOPER_GUIDELINES
rmdir docs
